In [1]:
import torch
tensor = torch.tensor([[1,2,3],[4,5,6]], dtype=torch.float32)
tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]])

### 索引和切片操作

In [2]:
# 去第一行
tensor[0]

tensor([1., 2., 3.])

In [5]:
# 取特定位置的元素
tensor[0][0]

tensor(1.)

In [6]:
tensor[0, 0]

tensor(1.)

In [7]:
# 取第二列所有元素
tensor[:,1]

tensor([2., 5.])

### 形状变换操作

In [11]:
reshaped = tensor.view(3, 2)
reshaped

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [13]:
# 将张量展平成一维
flattened = tensor.flatten()
flattened

tensor([1., 2., 3., 4., 5., 6.])

### 数学运算操作


In [14]:
# 张量加法
tensor_add = tensor + 10
tensor_add

tensor([[11., 12., 13.],
        [14., 15., 16.]])

In [15]:
# 张量乘法
tensor_mul = tensor * 2
tensor_mul

tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])

In [17]:
# 计算所有元素的和
tensor_sum = tensor.sum()
tensor_sum.item()

21.0

### 与其他张量的操作

In [19]:
# 矩阵乘法
tensor2 = torch.rand(3,2)
tensor3 = tensor @ tensor2
tensor3

tensor([[3.6430, 3.8825],
        [9.3357, 9.7184]])

In [20]:
# 张量矩阵乘法
tensor3 = torch.matmul(tensor, tensor2)
tensor3

tensor([[3.6430, 3.8825],
        [9.3357, 9.7184]])

### 条件判断和筛选

In [21]:
#  创建一个布尔掩码
mask = tensor > 3
mask

tensor([[False, False, False],
        [ True,  True,  True]])

In [23]:
# 筛选出符合条件的元素
filtered_tensor = tensor[tensor > 3]
filtered_tensor

tensor([4., 5., 6.])

In [26]:
# 将张量转移到 GPU
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
x = torch.tensor([1.0, 2.0, 3.0], device=device)
# 检验是否用带 cpu
torch.cuda.is_available()  # 返回 True 或 False

False

### 张量与 numpy 相互操作

In [27]:
import numpy as np

# NumPy 数组转换为 PyTorch 张量
numpy_array = np.array([[1, 2, 3], [4, 5, 6]])
numpy_array

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
tensor_from_numpy = torch.tensor(numpy_array, device=device)
tensor_from_numpy

tensor([[1, 2, 3],
        [4, 5, 6]])

In [29]:
# 修改 NumPy 数组，观察张量的变化（共享内存）
numpy_array[0, 0] = 100
numpy_array

array([[100,   2,   3],
       [  4,   5,   6]])

In [30]:
tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [34]:
# PyTorch 张量转换为 NumPy 数组
tensor3 = torch.tensor([[7, 8, 9], [10, 11, 12]], dtype=torch.float32)
tensor3

tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])

In [36]:
numpy_from_tensor = tensor3.numpy()
numpy_from_tensor

array([[ 7.,  8.,  9.],
       [10., 11., 12.]], dtype=float32)

In [37]:
# 修改张量，观察 NumPy 数组的变化（共享内存）
tensor3[0, 0] = 77
tensor3

[[77.  8.  9.]
 [10. 11. 12.]]


In [38]:
numpy_from_tensor

array([[77.,  8.,  9.],
       [10., 11., 12.]], dtype=float32)

In [40]:
# 不共享内存的情况（需要复制数据）
tensor_independent = torch.tensor([[13, 14, 15], [16, 17, 18]], dtype=torch.float32)
numpy_independent = tensor_independent.clone().numpy()
numpy_independent

array([[13., 14., 15.],
       [16., 17., 18.]], dtype=float32)

In [42]:
tensor_independent[0, 0] = 0
tensor_independent

tensor([[ 0., 14., 15.],
        [16., 17., 18.]])

In [43]:
numpy_independent

array([[13., 14., 15.],
       [16., 17., 18.]], dtype=float32)