In [2]:
import numpy as np
import torch
tensor = torch.ones(4, 4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [5]:
# 改变第一列
tensor[:,1] = 0
tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [13]:
# dim 0 行拼接 1 列拼接
t1 = torch.cat([tensor,tensor,tensor], dim=1)
t1

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])

In [17]:
# Arithmetic operations
# tensor.T 转置
y = tensor.T
y

tensor([[1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [18]:
# 表示对张量（tensor）进行矩阵乘法运算
# @ 是 Python 中用于矩阵乘法的运算符（等价于 torch.matmul() 或 tf.matmul()）
y1 = tensor @ tensor.T
y1

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [19]:
# @ 与 matmul() 等价
y2 = tensor.matmul(tensor.T)
y2

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [20]:
# 将所有的元素转化在 0-1 之间
# 表示创建一个与 y1 具有相同形状（shape）和数据类型（dtype）的新张量 y3，并且 y3 中的元素是从区间 [0, 1) 上均匀分布中随机生成的
y3 = torch.rand_like(y1)
y3

tensor([[0.6529, 0.8992, 0.2101, 0.1671],
        [0.2581, 0.4124, 0.6483, 0.7858],
        [0.2501, 0.7200, 0.9060, 0.3968],
        [0.8516, 0.1644, 0.8585, 0.9944]])

In [22]:
# torch.matmul 是 PyTorch 中用于矩阵乘法的函数，功能类似于 @ 运算符
# 第一个参数 tensor 和第二个参数 tensor.T 是参与乘法的两个张量（其中 tensor.T 是 tensor 的转置）
# out=y3 是一个可选参数，指定将运算结果直接存储到已存在的张量 y3 中，而不是创建一个新的张量
torch.matmul(tensor, tensor.T, out=y3)
y3

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [23]:
# 将 tensor 中每个位置的元素与自身相乘，结果存储在 z1 中。
z1 = tensor * tensor
z1

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [24]:
# .mul() 方法进行的逐元素乘法，功能与 * 运算符完全一致。
z2 = tensor.mul(tensor)
z2

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [27]:
# rand_like() 转化为 0-1 之间的元素，随机分布
z3 = torch.rand_like(tensor)
z3

tensor([[0.3181, 0.3430, 0.7731, 0.9322],
        [0.4838, 0.1650, 0.5481, 0.0198],
        [0.4677, 0.4041, 0.0169, 0.7904],
        [0.1576, 0.4871, 0.3780, 0.9852]])

In [28]:
# 元素相乘 存在 z3 中
torch.mul(tensor, tensor, out=z3)
z3

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [31]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


In [33]:
tensor.add_(6)
tensor

tensor([[7., 6., 7., 7.],
        [7., 6., 7., 7.],
        [7., 6., 7., 7.],
        [7., 6., 7., 7.]])

In [34]:
t = torch.ones(5)
print(f"t: {t}")
n = t.()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [35]:
# 在 cpu 上 tensor 和 numpy 共享内存地址，改边其中一个会改变另一个
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [51]:
import numpy as np
# NumPy array to Tensor
n = np.ones(5)
n

array([1., 1., 1., 1., 1.])

In [52]:
t = torch.from_numpy(n)
t

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [53]:
# np 数组的改变也会影响到 tensor
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
