### numpy
1. 安装 numpy

### 属性

In [3]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
print(arr.shape) # 数组的形状
print(arr.dtype) # 数组元素类型
print(arr.size) # 数组中元素个数
print(arr.ndim) # 数组纬度
print(type(arr)) # 数组类型
print(arr.itemsize) # 数组中每个元素字节数

(3, 3)
int64
9
2
<class 'numpy.ndarray'>
8


### 创建多维数组

In [9]:
data = [1,2,3]

print(f"data 内存地址：{id(data)}")
# 创建数组
arr1 = np.array(data)
print(f"arr1 内存地址：{id(arr1)}")

print(arr1.dtype)

data 内存地址：4688892608
arr1 内存地址：4380340848
int64


In [10]:
arr2 = np.array(arr1)
print(f"arr2 的内存地址：{id(arr2)}")

arr2 的内存地址：4688521968


In [12]:
arr3 = np.asarray(arr1)
print(arr3)
print(f"arr3 的内存地址：{id(arr3)}")

[1 2 3]
arr3 的内存地址：4380340848


In [7]:
arr4 = np.array([1, 2, 3])
arr4.dtype

dtype('int64')

In [12]:
arr5 = np.array([[1.5, 2, 4],[3, 6, 7]])
print(arr5)
arr5.dtype

[[1.5 2.  4. ]
 [3.  6.  7. ]]


dtype('float64')

In [15]:
arr6 = np.array([[1, 2, 4],[3, 6, 7]], dtype=complex)
arr6

array([[1.+0.j, 2.+0.j, 4.+0.j],
       [3.+0.j, 6.+0.j, 7.+0.j]])