### API 调用
1. zeros() 返回给定形状和类型的新数组，用 0 填充
2. ones() 返回给定形状和类型的数组，用 1 填充
3. empty() 返回给定形状和类型的为初始化的新数组

In [2]:
import numpy as np
arr = np.zeros((2,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [3]:
arr = np.ones((2,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
arr1 = np.empty((2,3))
arr1

array([[1., 1., 1.],
       [1., 1., 1.]])

1. zeros_like()
2. ones_like()
3. empty_like()

In [10]:
arr3 = np.zeros_like(arr1)
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
arr4 = np.ones_like(arr1)
arr4

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
arr5 = np.empty_like(arr)
arr5

array([[1., 1., 1.],
       [1., 1., 1.]])

1. full()
2. full_like()

In [25]:
arr1 = np.full((2,3), 5)
print(arr1)
arr2 = np.full_like(arr1, 3)
print(arr2)

[[5 5 5]
 [5 5 5]]
[[3 3 3]
 [3 3 3]]


In [26]:
arr = np.arange(0, 10, 2)
arr

array([0, 2, 4, 6, 8])