### API 调用
1. zeros() 返回给定形状和类型的新数组，用 0 填充
2. ones() 返回给定形状和类型的数组，用 1 填充
3. empty() 返回给定形状和类型的为初始化的新数组

In [1]:
import numpy as np
arr = np.zeros((2,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [3]:
arr = np.ones((2,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
arr1 = np.empty((2,3))
arr1

array([[1., 1., 1.],
       [1., 1., 1.]])

1. zeros_like()
2. ones_like()
3. empty_like()

In [10]:
arr3 = np.zeros_like(arr1)
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
arr4 = np.ones_like(arr1)
arr4

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
arr5 = np.empty_like(arr)
arr5

array([[1., 1., 1.],
       [1., 1., 1.]])

1. full()
2. full_like()

In [25]:
arr1 = np.full((2,3), 5)
print(arr1)
arr2 = np.full_like(arr1, 3)
print(arr2)

[[5 5 5]
 [5 5 5]]
[[3 3 3]
 [3 3 3]]


In [26]:
arr = np.arange(0, 10, 2)
arr

array([0, 2, 4, 6, 8])

In [2]:
arr = np.arange(0, 2, 0.3)
print(arr)

[0.  0.3 0.6 0.9 1.2 1.5 1.8]


In [4]:
from numpy import pi
arr = np.linspace(0, 2, 9) # 0 - 2 之间生成 9 个数
print(arr)

x = np.linspace(0, 2 * pi, 100)
print(np.sin(x))

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]
[ 0.00000000e+00  6.34239197e-02  1.26592454e-01  1.89251244e-01
  2.51147987e-01  3.12033446e-01  3.71662456e-01  4.29794912e-01
  4.86196736e-01  5.40640817e-01  5.92907929e-01  6.42787610e-01
  6.90079011e-01  7.34591709e-01  7.76146464e-01  8.14575952e-01
  8.49725430e-01  8.81453363e-01  9.09631995e-01  9.34147860e-01
  9.54902241e-01  9.71811568e-01  9.84807753e-01  9.93838464e-01
  9.98867339e-01  9.99874128e-01  9.96854776e-01  9.89821442e-01
  9.78802446e-01  9.63842159e-01  9.45000819e-01  9.22354294e-01
  8.95993774e-01  8.66025404e-01  8.32569855e-01  7.95761841e-01
  7.55749574e-01  7.12694171e-01  6.66769001e-01  6.18158986e-01
  5.67059864e-01  5.13677392e-01  4.58226522e-01  4.00930535e-01
  3.42020143e-01  2.81732557e-01  2.20310533e-01  1.58001396e-01
  9.50560433e-02  3.17279335e-02 -3.17279335e-02 -9.50560433e-02
 -1.58001396e-01 -2.20310533e-01 -2.81732557e-01 -3.42020143e-01
 -4.00930535e-01 -4.58226522e-01 -5.1367739

In [9]:
arr = np.arange(12)
print(arr)
arr1 = arr.reshape(3, 4)
print(arr1)
arr2 = np.arange(24).reshape(2, 3, 4)
print(arr2)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
