In [7]:
import numpy as np
a = np.array([1, 2, 3])
print(a)
b = np.arange(3)
print(b)
c = a - b
print(c)

[1 2 3]
[0 1 2]
[1 1 1]


In [8]:
d = a ** 2
print(d)

[1 4 9]


In [12]:
e = 10 * np.sin(a)
print(e)
a <= 2

[8.41470985 9.09297427 1.41120008]


array([ True,  True, False])

In [13]:
A = np.array([[1, 1], [0, 1]])
B = np.array([[1, 2], [3, 4]])
C = A * B
C

array([[1, 2],
       [0, 4]])

In [14]:
D = A @ B
print(D)

[[4 6]
 [3 4]]


In [15]:
E = A.dot(B)
print(E)

[[4 6]
 [3 4]]


In [20]:
rg = np.random.default_rng(1)
a = np.ones((2, 3), dtype=int)
print(a)
a *= 3
print(a)
b = rg.random((2, 3))
print(b)
b +=a
print(b)
# UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'
# a += b
# print(a)

[[1 1 1]
 [1 1 1]]
[[3 3 3]
 [3 3 3]]
[[0.51182162 0.9504637  0.14415961]
 [0.94864945 0.31183145 0.42332645]]
[[3.51182162 3.9504637  3.14415961]
 [3.94864945 3.31183145 3.42332645]]


In [21]:
A = np.arange(12).reshape(3, 4)
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [22]:
A.sum(axis=0)

array([12, 15, 18, 21])

In [23]:
A.sum(axis=1)

array([ 6, 22, 38])

In [24]:
A.min(axis=0)

array([0, 1, 2, 3])

In [25]:
A.min(axis=1)

array([0, 4, 8])

In [26]:
A.cumsum(axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21]])

In [27]:
A.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])